version: '3.8'

services:
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes: 
            - db:/var/lib/postgresql/data
        networks:
            - todo_app-network
    backend:
        container_name: todo_app_backend
        image: nestjs-api-dev:1.0.0
        depends_on:
            - db
        build:
            context: .
            dockerfile: ./Dockerfile
        command: npm run start:debug
        environment:
            PGHOST: db
            PGUSER: postgres
            PGPASSWORD: postgres
            PGDATABASE: postgres
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - todo_app-network
        volumes:
            - .:/usr/src/app
        restart: unless-stopped

networks:
    todo_app-network:

volumes:
  db:
    driver: local